name: Security Scan with OWASP ZAP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Start Target App (Example)
        run: |
          docker run -d -p 3000:3000 vulnerables/web-dvwa

      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://localhost:3000'
          fail_action: false
          cmd_options: '-a'

      - name: Save ZAP Report
        run: |
          mkdir -p reports
          mv zap_report.html reports/

      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: zap-security-report
          path: reports/zap_report.html
